### ISSUE TITLE
Не работает поиск слов через sql

### ISSUE THREAD

**Issue by Almeonamy** [miyconst/Cyriller#24]
Развернул базу. Пытаюсь выполнить следующий запрос. Вне зависимости от поисковой строки в результате 0 строк. Если не использовать фильтрацию по Name, то строки отображаются корректно.
`SELECT *
  FROM [Cyriller].[dbo].[Words]
  where [Name] = 'Мария'`

**Comment by miyconst** [comment]
@Almeonamy, в MS-SQL для Unicode символов нужно использовать тип данных `nchar`, правильный запрос, должен выглядеть вот так:

```sql
SELECT * 
FROM [Cyriller].[dbo].[Words] 
WHERE [Name] = N'Мария'
```

Больше информации доступно тут - [UNICODE (Transact-SQL)](https://docs.microsoft.com/en-us/sql/t-sql/functions/unicode-transact-sql?view=sql-server-2017).

**Comment by Almeonamy** [comment]
Оу, спасибо большое. Я почему-то думал, что MS SQL полностью на Юникоде. Буду знать.

**Comment by miyconst** [comment]
>... что MS SQL полностью на Юникоде.

MS SQL и есть полностью на юникода, для этого и есть специальный тип данных `nchar`, который поддерживает юникоды.
