### ISSUE TITLE
.net standard

### ISSUE THREAD

**Issue by Kantuz001** [miyconst/Cyriller#25]
Текущая зависимость 4.6.1, было бы классно чтобы пакеты имели зависимость от .net standard 1.6, 2.0

**Comment by miyconst** [comment]
Работа начата в ветке [`master-refactoring`](https://github.com/miyconst/Cyriller/tree/master-refactoring), но когда смогу закончить - не известно.

**Comment by miyconst** [comment]
Готово в с выходом версии  `0.1.0`.

- [Выпус GitHub](https://github.com/miyconst/Cyriller/releases/tag/0.1.0).
- [NuGet пакет](https://www.nuget.org/packages/Miyconst.Cyriller/0.1.0).
