### ISSUE TITLE
Поменяйте, пожалуйста, лицензию на LGPL

### ISSUE THREAD

**Issue by Mogikan** [miyconst/Cyriller#26]
Указанная Вами лицензия GPL не позволяет использовать библиотеку в коммерческих продуктах, поскольку требует опенсорсить и выкладывать исходники платных продуктов. LGPL требует только выкладывания изменений в вашей библиотеке.

**Comment by miyconst** [comment]
Готово.

Новая лицензия - `LGPL-3.0`, но Вам нужно будет собирать сборку самостоятельно, так как изменить лицензию для выпущенного NuGet пакета невозможно.

Удачи в работе и не забывайте делиться вашим опытом использования Кириллера с другими!
