### ISSUE TITLE
Обработка цифр во входящей строке.

### ISSUE THREAD

**Issue by Velamont** [miyconst/Cyriller#33]
При использовании метода CyrResult `Decline(string phrase, GetConditionsEnum condition)` если в строке имеется цифра, то выкидывается следующая ошибка.
![image](https://user-images.githubusercontent.com/36071263/79325862-92621480-7f1a-11ea-88c2-c5a2c53fff7e.png)
Прошу добавить возможность пропускать обработку цифровых значений в строке.

**Comment by BorzillaR** [comment]
Тоже самое происходит, если есть ковычка, и даже союз "и". Если слова в словаре нет, то просто исключение кидается. В ковычках часто пишутся названия организаций и было бы здорово, если бы эти названия оставались как есть, а союзы просто оставлялись как есть.

**Comment by miyconst** [comment]
![image](https://user-images.githubusercontent.com/6435556/175002068-9539e48f-2560-414d-9bd1-0ca1f5163fa3.png)
Робота над проектом повністю зупинена доки москальськи виродки не заберуться з України і не сплатять репарації.
