### ISSUE TITLE
Обновить версию библиотеки в NuGet, чтобы включить последний коммит

### ISSUE THREAD

**Issue by flosca** [miyconst/Cyriller#35]
Привет. Спасибо за библиотеку, она классная. Заметил один нюанс:

После релизной версии `0.1.0` в этом репозитории есть коммит, который правит баг с отчеством вида `<имя> оглы`.

До регулярных выражений там использовалась функция `StartsWith` вместо `EndsWith`, в связи с чем суффикс `оглы` тоже начинает склоняться. Это было поправлено в коммите https://github.com/miyconst/Cyriller/commit/5e1a370196e78302f33e12f6b0b5d85aa1e83a67#diff-2ed3fdfeb3fea71239bdd5be496e46f2L119

Просьба выложить в `NuGet` версию, включающую этот исправляющий ошибку коммит.

**Comment by miyconst** [comment]
Готово - [Кириллер 0.1.1](https://github.com/miyconst/Cyriller/releases/tag/0.1.1).

NuGet пакет еще на стадии валидации - [Miyconst.Cyriller 0.1.1](https://www.nuget.org/packages/Miyconst.Cyriller/0.1.1).
