### ISSUE TITLE
XML documentation file

### ISSUE THREAD

**Issue by gogijan** [miyconst/Cyriller#37]
В nuget пакет не включена XML документация, из-за этого очень неудобно пользоваться библиотекой, особенно выбирать падежи с названиями на английском без русского пояснения.
Пришлось скачать исходники и собрать самостоятельно.
Я про опцию сборщика "XML documentation file":
https://stackoverflow.com/questions/32994598/how-to-include-documentation-in-dll-to-show-method-summary-in-unity3d

**Comment by miyconst** [comment]
Благодарю за информацию! По возможности исправлю и выложу новый пакет.
