### ISSUE TITLE
Дата строкой

### ISSUE THREAD

**Issue by mrmaxonline** [miyconst/Cyriller#38]
В дополнение к https://github.com/miyconst/Cyriller/issues/36 предлагаю сделать возможность формирования даты строкой вида "девятое сентября  две тысячи двадцатого года" одним методом

**Comment by miyconst** [comment]
![image](https://user-images.githubusercontent.com/6435556/175002068-9539e48f-2560-414d-9bd1-0ca1f5163fa3.png)
Робота над проектом повністю зупинена доки москальськи виродки не заберуться з України і не сплатять репарації.
