### ISSUE TITLE
Newtonsoft.Json 11

### ISSUE THREAD

**Issue by mrmaxonline** [miyconst/Cyriller#39]
Просьба по возможности в пакете сделать зависимость с понижением версии от с 12 до 11, т.к. есть еще проекты, в которые не перешли на 12 версию

**Comment by miyconst** [comment]
![image](https://user-images.githubusercontent.com/6435556/175002068-9539e48f-2560-414d-9bd1-0ca1f5163fa3.png)
Робота над проектом повністю зупинена доки москальськи виродки не заберуться з України і не сплатять репарації.
