### ISSUE TITLE
Не склоняются слова

### ISSUE THREAD

**Issue by marktingarkada** [miyconst/Cyriller#4]
Системно не корректно склоняются следующие слова:
турбина
дельфинарий
бестиарий

ворота - нет в словаре

**Comment by miyconst** [comment]
@marktingarkada спасибо за выявление ошибок.

- Слова `турбина`, `дельфинарий`, `бестиарий` исправлены.
- Слово `ворота`, уже есть в словаре, и склоняется правильно. У данного слова нет единствернного числа.
