### ISSUE TITLE
Ошибка творительного падежа

### ISSUE THREAD

**Issue by PavlychevV** [miyconst/Cyriller#40]
<img width="260" alt="Снимок экрана 2022-02-25 в 12 01 32" src="https://user-images.githubusercontent.com/44994888/155686348-0e1bc224-a34f-478e-a58d-e6527f943394.png">
 
С моей нетипичной фамилией ошибается при попытке склонения в творительный падеж.
Правильно — Павлычевым

**Comment by miyconst** [comment]
![image](https://user-images.githubusercontent.com/6435556/175002068-9539e48f-2560-414d-9bd1-0ca1f5163fa3.png)
Робота над проектом повністю зупинена доки москальськи виродки не заберуться з України і не сплатять репарації.

**Comment by PavlychevV** [comment]
Z

**Comment by PavlychevV** [comment]
Хрюкни
