### ISSUE TITLE
Ошибка определения рода по имени

### ISSUE THREAD

**Issue by OverchenkoDev** [miyconst/Cyriller#44]
Здравствуйте! Столкнулся с ошибкой при использовании данного метода:
`var autoGender = CyrNounCollection.Get(firstName, out CasesEnum casesEnum, out NumbersEnum number);`

Если передавать firstName = "Петр", то данный метод возвращает объект с Name = "Петра" и женским родом.
В базе, по которой он смотрит, отсутствует имя Пётр?

**Comment by miyconst** [comment]
![image](https://user-images.githubusercontent.com/6435556/175002068-9539e48f-2560-414d-9bd1-0ca1f5163fa3.png)
Робота над проектом повністю зупинена доки москальськи виродки не заберуться з України і не сплатять репарації.

**Comment by OverchenkoDev** [comment]
Раз так, значит вам не место среди опенсорс-комьюнити. Разработка != политика, к тому же вы и сам "москаль".
