### ISSUE TITLE
Регистр букв

### ISSUE THREAD

**Issue by iamxor** [miyconst/Cyriller#5]
Привет!
Прежде всего хочу поблагодароить за весьма толковое и полезное приложение!

К примеру склоняем город - Петропавловск-Камчатский

```json
[{
    "Nominative": "Петропавловск-Камчатский",
    "Genitive": "Петропавловска-камчатского",
    "Dative": "Петропавловску-камчатскому",
    "Accusative": "Петропавловск-Камчатский",
    "Instrumental": "Петропавловском-камчатским",
    "Prepositional": "Петропавловске-камчатском",
    "Именительный": "Петропавловск-Камчатский",
    "Родительный": "Петропавловска-камчатского",
    "Дательный": "Петропавловску-камчатскому",
    "Винительный": "Петропавловск-Камчатский",
    "Творительный": "Петропавловском-камчатским",
    "Предложный": "Петропавловске-камчатском"
}]
```

В результате вторая часть города не всегда как в оригинале тоесть в нижнем регистре.

**Comment by miyconst** [comment]
@iamxor, я рад, что есть пользователи приложения и спасибо за сообщение об ошибке.

Ошибку исправил, теперь составные слова (с дефисом) обрабатываются частями, а не как одно целое слово.

[http://cyriller.2try.ws/Decline/Noun?w=Петропавловск-Камчатский](http://cyriller.2try.ws/Decline/Noun?w=%D0%9F%D0%B5%D1%82%D1%80%D0%BE%D0%BF%D0%B0%D0%B2%D0%BB%D0%BE%D0%B2%D1%81%D0%BA-%D0%9A%D0%B0%D0%BC%D1%87%D0%B0%D1%82%D1%81%D0%BA%D0%B8%D0%B9).
