### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by iamxor** [miyconst/Cyriller#6]
День добрый!
Попробуйте просклонять Улан-Удэ или  Санкт-Петербург
http://cyriller.2try.ws/Decline/Phrase?w=%D1%83%D0%BB%D0%B0%D0%BD-%D1%83%D0%B4%D1%8D

**Comment by miyconst** [comment]
Ошибка исправлена в `0.0.2`, еще раз спасибо.

NuGet: [Miyconst.Cyriller 0.0.2](https://www.nuget.org/packages/Miyconst.Cyriller/0.0.2).
